# string = "hello python"
# string = """hello world"""
# print(string.capitalize())
# print(string.casefold())
# print("string".center(11,"*"))
# print(string.count())===============
# print(string.encode())
# print(string.endswith("byy"))
# print(string.startswith("Hello"))
# print(string.format())
# print(string.index([5]))===============
# print(string.isalnum())
# print(string.isalpha())
# print(string.isascii())
# print(string.isdecimal())
# print(string.isdigit())
# print(string.isupper())
# print(string.islower())
# print(string.upper())
# print(string.title())
# print(string.split('-'))
# print("string".zfill(10))
# str2 = "hello java"
# print(string.join(str2))
# print("good morning".join("st"))
# print(string)

string = """ hello world """
# print(string)
# print(len(string))
# print(string.capitalize())
# print(string.casefold())
# print(string.title())
# print("string".center(9,"*"))
# print(string.count("h"))
# print(string.endswith("d"))
# print(string.startswith("h"))
# print(string.upper())
# print(string.lower())
# print("abc123".isalnum())
# print("abc123".isalpha())
# print("abe12&3".isascii())
# print("124".isdecimal())
# print("12345".isdigit())
# print(string.islower())
# print(string.isupper())
# print("abc".isnumeric())
# print(string.isspace())
# print(string.index("e"))
# print(string[-1])
# print(string[1:5])
# print("good morning".join(string))
print(string.split('----'))

