# string = "hello python"
# string = """hello world"""
# print(string.capitalize())
# print(string.casefold())
# print("string".center(11,"*"))
# print(string.count())===============
# print(string.encode())
# print(string.endswith("byy"))
# print(string.startswith("Hello"))
# print(string.format())
# print(string.index([5]))===============
# print(string.isalnum())
# print(string.isalpha())
# print(string.isascii())
# print(string.isdecimal())
# print(string.isdigit())
# print(string.isupper())
# print(string.islower())
# print(string.upper())
# print(string.title())
# print(string.split('-'))
# print("string".zfill(10))
# str2 = "hello java"
# print(string.join(str2))
# print("good morning".join("st"))
# print(string)

# string = """ hello world """
# print(string)
# print(len(string))
# print(string.capitalize())
# print(string.casefold())
# print(string.title())
# print("string".center(9,"*"))
# print(string.count("h"))
# print(string.endswith("d"))
# print(string.startswith("h"))
# print(string.upper())
# print(string.lower())
# print("abc123".isalnum())
# print("abc123".isalpha())
# print("abe12&3".isascii())
# print("124".isdecimal())
# print("12345".isdigit())
# print(string.islower())
# print(string.isupper())
# print("abc".isnumeric())
# print(string.isspace())
# print(string.index("e"))
# print(string[-1])
# print(string[1:5])
# print("good morning".join(string))
# print(string.split('----'))


str = "hello world"
# print(str)
# print(str.capitalize())
# print(str.casefold())
# print(str.center(5,"*"))
print(str.count("d"))
# print(str.endswith("d"))
# print(str.startswith("y"))
# print(str.title())
# print(str.index("d"))
# print(len(str))
# print("abc12".isalnum())
# print("abc".isalpha())
# print("abc123".isascii())
# print("123457".isdecimal())
# print("123".isdigit())
# print("123".isnumeric())
# print("hello".upper())
# print("hello".isupper())
# print("HELLO".lower())
# print("hello".islower())
# print("hello".zfill(10))
# print(str.split("-"))
# print(str[1:])
# print(str[1:5])
# print(str[:-1])
# print(str[-5::])
# print("india".join(str))
# print(str.encode())
# print(str.format())
# print("zeel".center(10,"*"))
# str1 = 'hello'
# print(str1)