# Generated by Django 5.2.8 on 2025-12-18 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='image',
            field=models.ImageField(default='test', upload_to='image'),
        ),
    ]
