# Generated by Django 5.2.9 on 2025-12-03 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=60)),
                ('age', models.IntegerField()),
                ('subject', models.CharField()),
                ('class_room', models.CharField()),
            ],
        ),
    ]
