# Generated by Django 5.2.8 on 2025-12-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('rollno', models.IntegerField()),
                ('subject', models.CharField(max_length=70)),
                ('marks', models.IntegerField()),
            ],
        ),
    ]
