# Generated by Django 6.0 on 2025-12-05 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='dept',
            field=models.CharField(max_length=50),
        ),
    ]
